### ISSUE TITLE
ipfs feedback

### ISSUE THREAD

**Issue by jbenet** [insanity54/ipfs-play#1]
please let us know any problems + how we can improve ipfs-api. Lot's of stuff can be improved, so let us know whatever you struggle with!

**Comment by insanity54** [comment]
I found ipfs-api pretty easy to work with. If there was something I struggled with, it wasn't the api but the api's docs. https://github.com/ipfs/js-ipfs-api/blob/master/README.md I was looking at the curl command. It shows usage and an example, but not a description of what it does. Maybe it's just the version of go-ipfs I have, but `curl` isn't available in the go-ipfs command line either so I couldn't figure out why one would want to use such a command. My assumption based on the example response is that the curl command returns raw data given a hash address, but I'd be afraid to use it without knowing it's real intent.

That's minor though, if I wanted to know bad enough I could just read the source. For this project using ipfs.add and ipfs.cat, it was easy for me to work with!
